### ISSUE TITLE
Fatal: Cannot add project

### ISSUE THREAD

**Issue by th3fallen** [Block8/PHPCI#1007]
When adding a project with github application configured, after filling out all data i get this... 

Sorry, there was a problem
SQLSTATE[HY000]: General error: 1364 Field 'access_information' doesn't have a default value

**Comment by mrjgreen** [comment]
I seem to have had this issue too. I basically fixed it by taking the NOT NULLs off all text fields and removing NOT NULL and adding DEFAULT NULL to the datetime fields and adding DEFAULT '' to access_information and last_commit.

On `project`:
    SQLSTATE[HY000]: General error: 1364 Field 'access_information' doesn't have a default value
    SQLSTATE[HY000]: General error: 1364 Field 'last_commit' doesn't have a default value

On `build`:
    SQLSTATE[HY000]: General error: 1364 Field 'log' doesn't have a default value
    SQLSTATE[HY000]: General error: 1364 Field 'started' doesn't have a default value
    SQLSTATE[HY000]: General error: 1364 Field 'finished' doesn't have a default value
    SQLSTATE[HY000]: General error: 1364 Field 'commit_message' doesn't have a default value
    SQLSTATE[HY000]: General error: 1364 Field 'extra' doesn't have a default value

**Comment by th3fallen** [comment]
i did the same @mrjgreen i just wanted to make it known that this is an issue... not sure how that made it into a stable release considering the installer doesn't even work....

Very disappointing.

**Comment by mavimo** [comment]
@th3fallen @mrjgreen can you investigate how to solve the issue on PHP side without change the DB definition? I suppose was an issue on "filled value" on the project & build objects.. thanks!

**Comment by dodiaraculus** [comment]
Seems to be a mysql/php type error.
<pre>
SQLSTATE[HY000]: General error: 1364 Field 'log' doesn't have a default value
SQLSTATE[HY000]: General error: 1364 Field 'started' doesn't have a default value
SQLSTATE[HY000]: General error: 1364 Field 'finished' doesn't have a default value
SQLSTATE[HY000]: General error: 1364 Field 'commit_message' doesn't have a default value
SQLSTATE[HY000]: General error: 1364 Field 'extra' doesn't have a default value
</pre>
Have you tried setting a default value in mysql? I would recommend that you use phpmyadmin.

**Comment by curtisdf** [comment]
Some newer versions of MySQL have `sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES` in their default `my.cnf` config files.  Removing the `,STRICT_TRANS_TABLES` part and restarting MySQL takes care of this problem.

The real issue is that PHPCI attempts to rely on MySQL to populate default values on some (many?) of its fields during `INSERT` queries, instead of explicitly setting the values for each field.  `STRICT_TRANS_TABLES` causes MySQL to barf on these inserts.  Unfortunately, this is now the default for MySQL.

To make PHPCI's installer work out-of-the-box for the maximum number of users, this needs to be explored some more. Maybe when the database for PHPCI is created, the `CREATE TABLE` statements need to explicitly set a default for every field.  Or get rid of `NOT NULL` for fields that are not always required.  Or rework the `INSERT` statements so they explicitly set a value for every field.
