### ISSUE TITLE
Behat support

### ISSUE THREAD

**Issue by meadsteve** [Block8/PHPCI#101]
Behat (http://behat.org/) is a fairly popular BDD framework for PHP. It'd be good to get a plugin written for this at some point in the future.

**Comment by dutchiexl** [comment]
I created a plugin for HTML reporting, It works out of the box. It creates an array of suits, features, steps ... that can be rendered in a single template.

Since this works closely with symfony I used twig as a dependency. You can check it out or fork me. I could use some help creating a nice report.

I also added the plugin to packagist

https://github.com/dutchiexl/BehatHtmlFormatterPlugin.git

https://packagist.org/packages/emuse/behat-html-formatter
