### ISSUE TITLE
 Development prospects

### ISSUE THREAD

**Issue by OxGroup** [Block8/PHPCI#1199]
Will the product be developed in the future? Not at all is done no work. Pile of open requests, a lot of problems and no solutions. Last update a few months ago, which is associated with the addition of the text "test" in the readme. This lol.

**Comment by GenericStudent** [comment]
+1 I would also like to know as I'd like to contribute time but not if it is left high and dry.

**Comment by REBELinBLUE** [comment]
I keep bugging @dancryer on Google Hangouts.... I have prodded him again

**Comment by REBELinBLUE** [comment]
Dan has fixed the PHPCI install. I know he is really busy with his business right now. I am away for the holiday weekend but I plan to try fixing a few issues next week

**Comment by dancryer** [comment]
PHPCI development tends to come in waves - we get a wave of activity, followed by a period of quiet. This is usually driven by my personal work schedule, as relatively little happens when I am too busy to be actively involved day to day. 

To the best of my knowledge, v1.6 is relatively stable barring a few environment specific issues. v1.7 will be out shortly with a range of improvements.

**Comment by dancryer** [comment]
P.s. If you want to get involved, please do get in touch. Drop me an email via hello@phptesting.org with an outline of how you'd like to help. 👍
