### ISSUE TITLE
SwiftMailer errors after latest merge

### ISSUE THREAD

**Issue by mikebronner** [Block8/PHPCI#373]
Getting the following errors after pulling this morning's changes:

```
ci:PHPCI localadmin$ sudo /usr/bin/php /Library/Server/Web/Data/Sites/PHPCI/console phpci:run-builds
Password:
string(113) "export GIT_SSH="/Library/Server/Web/Data/Sites/PHPCI/PHPCI/build/project2-build199.sh" && git clone -b %s %s "%s""
Cloning into '/Library/Server/Web/Data/Sites/PHPCI/PHPCI/build/project2-build199'...
remote: Counting objects: 8777, done.
remote: Compressing objects: 100% (4769/4769), done.
remote: Total 8777 (delta 3887), reused 7744 (delta 3416)
Receiving objects: 100% (8777/8777), 6.62 MiB | 2.18 MiB/s, done.
Resolving deltas: 100% (3887/3887), done.
Checking connectivity... done.
Checking out files: 100% (4728/4728), done.
Note: checking out '24c5b7a4dfd1e2af6e3c40d4ddfe256d1e3a20ac'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 24c5b7a... Reinstalled PHPSpec
phpcpd 2.0.0 by Sebastian Bergmann.

0.00% duplicated lines out of 6065 total lines of code.

Time: 753 ms, Memory: 6.75MbPHP Fatal error:  Cannot redeclare class Swift in /Library/Server/Web/Data/Sites/PHPCI/vendor/swiftmailer/swiftmailer/lib/classes/Swift.php on line 19
PHP Stack trace:
PHP   1. {main}() /Library/Server/Web/Data/Sites/PHPCI/vendor/phpspec/phpspec/bin/phpspec:0
PHP   2. require() /Library/Server/Web/Data/Sites/PHPCI/vendor/phpspec/phpspec/bin/phpspec:13
PHP   3. ComposerAutoloaderInit39cdebe88d99fbeeac4d387d4e4dbbc9::getLoader() /Library/Server/Web/Data/Sites/PHPCI/vendor/autoload.php:7
PHP   4. composerRequire39cdebe88d99fbeeac4d387d4e4dbbc9() /Library/Server/Web/Data/Sites/PHPCI/vendor/composer/autoload_real.php:52
PHP   5. require() /Library/Server/Web/Data/Sites/PHPCI/vendor/composer/autoload_real.php:61
PHP   6. require() /Library/Server/Web/Data/Sites/PHPCI/vendor/swiftmailer/swiftmailer/lib/swift_required.php:22
```

**Comment by RealBerd** [comment]
Did anyone solve it?

**Comment by tjantika** [comment]
I had a similar problem and did a bit investigation on it. In my symfony project the autoload.php file has the line require_once __DIR__.'/../vendor/swiftmailer/lib/classes/Swift.php'; and that fails because Swift-class has already been loaded at that point. What is loading that file is the composer generated autoloader phpci/vendor/autoload.php (end eventually defined in phpci/vendor/composer/autoload_files.php and in phpci/vendor/swiftmailer/swiftmailer/lib/swift_required.php). Adding a class_exists() -check around that require Swift line on the projects autoload.php could help, but only if the Swift version included by phpci is compatible with the version needed by the project under testing.

To me that may sound even a bigger problem which has nothing to do with Swift. Should my project, that I want to test with phpci, be compatible with all the same versions of the libraries that it shares with phpci? Phpci uses many symfony components and I've already noticed problems with for example the console componets Command-class for which my project uses different version than phpci requires.

I will investigate next if sing an external phpunit, and not the one under phpci/verdir dir, would help.

**Comment by dancryer** [comment]
Closing this on the assumption it is fixed and/or no longer relevant by now. Feel free to reopen if this assumption is incorrect.
