### ISSUE TITLE
Build_path is / in Shell plugin with multiple commands and not the real path

### ISSUE THREAD

**Issue by tvbeek** [Block8/PHPCI#509]
I try to use the Shell plugin to execute some commands. But I didn't get the base path

I place $this->phpci->log($command); in PHPCI/Plugin/Shell.php on line 77 to display the command.
To test it I used the next configuration with multiple commands
```
    shell:
        - "echo $PHPCI_BUILD_PATH"
        - "echo $BUILD_PATH"
        - "echo %BUILD_PATH%"
        - "echo %build_path%"
```

The result is:
```
echo $PHPCI_BUILD_PATH
/
echo $BUILD_PATH

echo /
/
echo %build_path%
EXCEPTION: Warning: sprintf(): Too few arguments in /path/to/phpci/PHPCI/Helper/BaseCommandExecutor.php line 68
```
If I remove the last line from the config, I get the same but without that error part of this result

It use / as the BUILD_PATH and not /path/to/phpci/PHPCI/build/projectx-buildy

**Comment by axka** [comment]
+1
Running into exact the same issue.

**Comment by dancryer** [comment]
I think this issue is actually not an issue at all. The build log (stored in the database) strips out the full build path to make all paths in the log relative.

For example:

`/path/to/phpci/PHPCI/build/1929/Some/File.php` will be converted to `Some/File.php` for display. 

However, the paths that the plugins themselves use are the full paths.

**Comment by Adirelle** [comment]
@dancryer Although I understand the logic behind this replacement, this just seems to add confusion when you're trying to debug any plugin.
