### ISSUE TITLE
Allow binary discovery to be influenced

### ISSUE THREAD

**Issue by leewillis77** [Block8/PHPCI#788]
Currently, checking out PHPCI, and running composer install will pull in a number of dependencies, including PHP_CodeSniffer. This creates a phpcs executable in vendor/bin. 

This binary trumps anything else that may be on the system, making it difficult to run sniffs that depend on more recent versions of phpcs since PHPCI will always use it's local copy, not the system installed version.

I'm not sure what the solution is here, but I'd prefer something cleaner than my current solution (rm vendor/bin/phpcs) :)

**Comment by dancryer** [comment]
The best thing to do if you just want to run PHPCI (rather than work on PHPCI itself) is to install it without dev requirements:

`./composer.phar create-project block8/phpci phpci --keep-vcs --no-dev`

That will mean it won't install PHPCS, PHPUnit, etc. as they're dev-only requirements. Then PHPCI will fall back to finding the binaries elsewhere.

**Comment by leewillis77** [comment]
Ah, OK - it hadn't occurred to me that they might be dev only dependencies ;) Now cleanly removed - thanks!
