### ISSUE TITLE
What to do with new plugins

### ISSUE THREAD

**Issue by tvbeek** [Block8/PHPCI#794]
I was thinking about the way to add new plugins. We have the core plugins but one of the beautiful parts of PHPCI is the option to add other plugins.

Specially after #760 and #761 it is good to think about the way to add them because now we have a start with the plugins.
In short we have 3 options:
1. Don't add them
2. Add them on the same way as core plugins
3. Add them in a separated list

My opinion is:

1. If we don't add them, we don't support people to create plugins and share there knowledge and power. I think it's good for PHPCI to support people to create a plugin and share it.

2. If we add them on the same way as the core plugins it isn't clear for the users that we didn't made it and aren't responsible for the plugin. That isn't smart because it is possible that a plugin has bugs and we can't fix it. We combine the reputation of PHPCI with external plugins what is a risk and in my opinion not good.

3. If we add a separated list with plugins form other people. On this way we support people to create plugins and share them with other peoples. Also we make clear that PHPCI doesn't maintain them and isn't responsible for bugs. I think that we should create some rules (like if you install the plugin the configuration need to be clear or will give a clear message if you miss some parts. How to name the plugin, update if PHPCI update, ...)

@Block8/phpci-contributors what is your opinion?

(This issue is basically for @Block8/phpci-contributors but I also like other people to give an opinion.)

**Comment by mavimo** [comment]
My personal opinioni is for 2, but a plugin to be added need also to respect some rules:

 * CS
 * Tests
 * Docs

IMHO we need also to rethink the [plugin interface](https://github.com/Block8/PHPCI/blob/master/PHPCI%2FPlugin.php#L18-L21), actually only ```execute``` method is defined, but plugins require also some other object (```Phpci```, ```Build```, ```Project```, ...) actually passed in constructor. I think have a factory with defined parameters passed to plugin can move the plugin maintainers in the right way, and define a contract between plugin and PHPCI project can be useful to grant compatibility for "long time".
Plugin also need to expose a result information that can be used in UI (if they need to report some information), otherwise we need hight coupling between PHPCI project (that have the UI) and plugins (eg PHCS / PHPUnit report).

I disagree on plugin inclusion in the PHPCI core because they require maintenance and maybe not all maintainers have use case where they can test each plugin, anche this can generate immobility on project changes.

**Comment by tvbeek** [comment]
@mavimo Do you mean 2 or 3 (I updated the issues because the numbers went wrong so you got 1,1,2 and not 1,2,3)

**Comment by mavimo** [comment]
@tvbeek edited, I mean 3 (Add them in a separated list)

**Comment by mavimo** [comment]
@dancryer @meadsteve @mikebronner @jfi any opinion?

**Comment by dancryer** [comment]
Whilst it does come with a maintenance burden, I'd prefer to keep the majority of useful plugins built into PHPCI - it gives us a lot more flexibility, and a better "out of the box" experience for our users.

In the case of external plugins, they should install their own respective dependencies. I don't think we should "suggest" installation of third party plugins that we can't ensure are properly maintained.

**Comment by tvbeek** [comment]
Maybe we need to add this to the wiki together with some basic information about creating a plugin
